name: Frontend ForgotPassword Test

on:
  push:
    paths:
      - 'src/Pages/**'
      - 'src/hooks/**'
      - 'src/test/forgotPassword.test.tsx'
  pull_request:
    paths:
      - 'src/Pages/**'
      - 'src/hooks/**'
      - 'src/test/forgotPassword.test.tsx'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: npm ci
      - name: Run forgotPassword test
        run: npm run test:unit -- src/test/forgotPassword.test.tsx -- --run --reporter default