name: Frontend Header Test

on:
  push:
    paths:
      - 'src/Components/Header.tsx'
      - 'test case/Header.test.tsx'
      - '.github/workflows/frontend-header-test.yml'
  pull_request:
    paths:
      - 'src/Components/Header.tsx'
      - 'test case/Header.test.tsx'
      - '.github/workflows/frontend-header-test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Run Header unit test (Vitest)
        env:
          CI: true
        run: npx vitest run "test case/Header.test.tsx"
        working-directory: ./