name: Frontend SignIN Test

on:
  push:
    paths:
      - 'src/Pages/SignIN.tsx'
      - 'test case/SignIN.test.tsx'
      - '.github/workflows/frontend-signin-test.yml'
  pull_request:
    paths:
      - 'src/Pages/SignIN.tsx'
      - 'test case/SignIN.test.tsx'
      - '.github/workflows/frontend-signin-test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Run SignIN unit test (Vitest)
        env:
          CI: true
        run: npx vitest run "test case/SignIN.test.tsx"
        working-directory: ./